version: '3.4'

#VARIAVEIS COMUNS DENTRO DO COMPOSE
x-common-variables:
  &db-variables
  MYSQL_DATABASE: Users
  MYSQL_USERNAME: root
  MYSQL_ROOT_PASSWORD: root

networks:
  db:
  router:

services:
  router:
    build: router\nginx
    image: router-img-nginx
    ports:            #PORT:
      - "1111:8080"   #REQUEST ENTRY-POINT [PORTA DE ENTRADA DO REQUESTS]
    hostname: router
    tty: true
    environment:
      - NGINX_PORT=8080
    depends_on:
      - webapp
    networks:
      - router