version: '3.4'

#VARIAVEIS COMUNS DENTRO DO COMPOSE
x-common-variables:
  &db-variables
    MYSQL_DATABASE: Users
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: root

networks:
  db:

services:
  mysql:
    image: mysql:5.7.22
    #ports:
    # - "8888:3306" #>>> This port is used only for debug
    hostname: mysql
    environment:
      *db-variables
    networks:
      - db
  
  webapp:
    build: webapp
    image: web-img
    ports:
      - "8080:8080"
    hostname: web
    tty: true
    depends_on:
      - mysql
    environment:
      <<: *db-variables
      DB_PORT: tcp://mysql:3306
      DB_NOME_BANCO: Users
    networks:
      - db